pub mod academic_writing;
pub mod active_researcher;
pub mod app_lock;
pub mod artifacts;
pub mod arxiv;
pub mod ccf;
pub mod chat;
pub mod chat_tools;
pub mod citation_graph;
pub mod code;
pub mod data_backup;
pub mod desktop_assistant;
pub mod desktop_assistant_actions;
pub mod desktop_assistant_assets;
pub mod desktop_assistant_capture_overlay;
pub mod desktop_assistant_inbox;
pub mod desktop_assistant_sessions;
pub mod desktop_assistant_source;
pub mod desktop_assistant_terminology;
pub mod evidence;
pub mod experiment;
pub mod export;
pub mod field_dynamics;
pub mod github_project;
pub mod journal;
pub mod knowledge;
pub mod knowledge_graph;
pub mod knowledge_hypothesis;
pub mod knowledge_ideas;
pub mod knowledge_notes;
pub mod knowledge_plan_status;
pub mod memory;
pub mod memory_checkpoints;
pub mod memory_privacy;
pub mod misc;
pub mod paper_analysis_prompts;
pub mod paper_analysis_text;
pub mod paper_artifacts;
pub mod paper_corpus;
pub mod paper_cross_analysis;
pub mod paper_figure_pages;
pub mod paper_figures;
pub mod paper_notes;
pub mod paper_search;
#[cfg(test)]
mod paper_search_live_eval;
mod paper_search_plan;
#[cfg(test)]
mod paper_search_plan_eval;
mod paper_search_query_expansion;
mod paper_search_ranking;
mod paper_search_response_cache;
mod paper_search_snippets;
mod paper_search_strategy;
pub mod paper_text;
pub mod papers;
pub mod research_context;
pub mod settings;
pub mod skills;
pub mod source;
pub mod submission;
pub mod survey_support;
pub mod sync;
pub mod token_usage;
pub mod translation;
pub mod update;
pub mod webdav_sync;
pub mod workbench;
pub mod writing;
pub mod writing_drafts;
pub mod writing_support;
pub mod writing_versions;
